name: build

on:
  push
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Build app for release
        run: msbuild shutdown-timer.csproj -t:rebuild -verbosity:diag -property:Configuration=Release -property:Platform=x64
